# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_id', models.CharField(max_length=25, unique=True)),
                ('guid', models.UUIDField(unique=True)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.IntegerField()),
                ('picture_url', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('eye_color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('about', models.TextField()),
                ('greeting', models.TextField()),
                ('registered_at', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
