# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='people.Person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='people.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friendrelationship',
            unique_together=set([('person_1', 'person_2')]),
        ),
    ]
