# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20171109_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('person', 'tag_name')]),
        ),
    ]
